AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.13

  Sample SAM Template for aws-cost-report

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  CostReportFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref CostReportSNSTopic
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /cost-report
            Method: get
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - "ce:GetCostAndUsage"
              - "sns:Publish"
            Resource: "*"

    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./cost_report
      DockerTag: python3.13-v1

  CostReportSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: "Cost Report Notifications"

  CostReportSNSTopicSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref CostReportSNSTopic
      Protocol: email
      Endpoint: "chikutaku.reiwa.2020@gmail.com"

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  # HelloWorldApi:
  #   Description: "API Gateway endpoint URL for Prod stage for Hello World function"
  #   Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  # HelloWorldFunction:
  #   Description: "Hello World Lambda Function ARN"
  #   Value: !GetAtt HelloWorldFunction.Arn
  # HelloWorldFunctionIamRole:
  #   Description: "Implicit IAM Role created for Hello World function"
  #   Value: !GetAtt HelloWorldFunctionRole.Arn
  # CostReportApi:
  #   Description: "API Gateway endpoint URL for Prod stage for Hello World function"
  #   Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"

  CostReportApi:
    Description: "API Gateway endpoint URL for Prod stage for Cost Report function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/cost-report/"
  CostReportFunction:
    Description: "Cost Report Lambda Function ARN"
    Value: !GetAtt CostReportFunction.Arn
  CostReportFunctionIamRole:
    Description: "Implicit IAM Role created for Cost Report function"
    Value: !GetAtt CostReportFunctionRole.Arn
